### PR TITLE
bump handlebars to ^4.0.14

### PR DESCRIPTION
**Pull request by pklingem**
see https://www.npmjs.com/advisories/755

### CODE REVIEW

**Comment by pklingem** [comment]
@ttacon any chance to get this merged?  Our only alternative is to fork the repo and publish a fork under the @articulate namespace and we'd prefer not to do that.

**Comment by ttacon** [comment]
This slipped off of my plate, thanks for the ping @pklingem!

**Comment by ttacon** [comment]
Published under 2.6.3

**Comment by pklingem** [comment]
thank you @ttacon!

**Pull request merged**
