### PR TITLE
move nodemon to dev

### PR DESCRIPTION
**Pull request by Jimmysh**

### CODE REVIEW

**Comment by ttacon** [comment]
HI @Jimmysh, thanks for the PR! Can you update the PR to leave `bull` and `bee-queue` as dependencies for now? We'll be revisiting them as `peerDependencies` soon, but do not want to make that change at this moment. If you can update the PR I'll get this merged right away. Cheers!

**Comment by ttacon** [comment]
Thanks for the PR - I'll be looking to merge this soon and will resolve the merge conflicts. Cheers!

**Comment by skeggse** [comment]
Landed in 485684e.

**Comment by skeggse** [comment]
Released in v2.8.2.

**Pull request closed without merging**
