### PR TITLE
fix(deps): upgrade moment to 2.29.4

### PR DESCRIPTION
**Pull request by roggervalf**
#### Changes Made
Upgrade moment to version 2.29.4 ref https://github.com/bee-queue/arena/pull/540, this one also changes the package in package.json file
#### Potential Risks

None
#### Test Plan

As it is a minor change version it should work as expected
#### Checklist

- [ ] I've increased test coverage
- [x] Since this is a public repository, I've checked I'm not publishing private data in the code, commit comments, or this PR.

### CODE REVIEW

**Comment by roggervalf** [comment]
please @bradvogel  when you get some chance

**Comment by bradvogel** [comment]
Unfortunately we're not able to review farther fixes in this repo. I filed https://github.com/bee-queue/arena/issues/546.

@roggervalf do you have an interest in being a maintainer?

**Comment by roggervalf** [comment]
hey @bradvogel, sure I can

**Comment by bradvogel** [comment]
@roggervalf Actually, could we merge https://github.com/bee-queue/arena/pull/540 instead? We don't need the update to package.json, as it uses the `^` syntax to specify the "latest minor version"

**Comment by roggervalf** [comment]
sure, it should be fine let me close this one

**Comment by roggervalf** [comment]
hey @bradvogel looks like the npm token is not longer [valid](https://github.com/bee-queue/arena/actions/runs/29556205754/job/87808745187)

**Comment by roggervalf** [comment]
btw @bradvogel this is my npm user rogger.794 so I can regenerate the token

**Comment by bradvogel** [comment]
@roggervalf I no longer have access to the npm or the github repos for this project.

@skeggse or @LewisJEllis ?

**Review by skeggse — APPROVED** [review]

**Comment by roggervalf** [comment]
hi @skeggse @LewisJEllis pls if you have access to npm package to add my user rogger.794 so I can regenerate the token to publish new versions

**Comment by bradvogel** [comment]
@guilhermemj @raphaelbs @akashbhalla @jordins @gabriel-mixmax - could one of you give @roggervalf npm maintainer permission on the bull-arena npm project?

**Comment by raphaelbs** [comment]
@roggervalf done! You should have received the invitation

**Pull request closed without merging**
