### PR TITLE
Bumped handlebars-helpers version to fix vulnerability.

### PR DESCRIPTION
**Pull request by eeVoskos**
Fix for vulnerability:
https://nodesecurity.io/advisories/745

Relates to [this](https://github.com/bee-queue/arena/pull/140) incomplete PR, but since its author is nowhere to be found for the past 2 months, I decided to make a new one.

### CODE REVIEW

**Comment by eeVoskos** [comment]
@skeggse could you please merge this? Thanks.

**Comment by skeggse** [comment]
Closes #140.

**Comment by skeggse** [comment]
Published as `v2.5.4`. Thanks for being persistent! This got lost in my inbox :disappointed:

**Comment by eeVoskos** [comment]
Well, I just hate those npm audit warnings 😁

**Pull request merged**
