### PR TITLE
feat(bull): support removing repeatable jobs

### PR DESCRIPTION
**Pull request by roggervalf**
#### Changes Made
Add new button to remove repeatable jobs if a job is linked to one
#### Potential Risks
None, this should be only be visible for bull package

#### Test Plan
Make sure there is not repeatable job in delayed state when you click remove repeatable button
#### Checklist

- [x] I've increased test coverage
- [x] Since this is a public repository, I've checked I'm not publishing private data in the code, commit comments, or this PR.

### CODE REVIEW

**Comment by roggervalf** [comment]
Prs requires at least 1 approval

**Comment by bradvogel** [comment]
@roggervalf I unfortunately have time to review. Is there someone else from your team that can review?

**Comment by roggervalf** [comment]
hi @bradvogel, could you please add @richardmaysundo?, he is from my team and can help on reviewing prs

**Comment by roggervalf** [comment]
can I also be added as a collaborator in https://www.npmjs.com/package/bull-arena? this is my user https://www.npmjs.com/~rogger.794

**Comment by bradvogel** [comment]
@roggervalf I made you admin on this repository. You can add whoever you'd like to.

**Review by richardmaysundo — APPROVED** [review]
LGTM, only need to rename variable 'r' here https://github.com/bee-queue/arena/pull/574/files#diff-e36254d8c0d26892d85dda23a915f524ec640aadfb50e7dc4bc0abe1894934dcR140

**Pull request merged**
