### PR TITLE
fix: fixes misplaced parameters

### PR DESCRIPTION
**Pull request by bradvogel**
#### Changes Made
Fixes misplaced parameters that I overlooked when reviewing https://github.com/bee-queue/arena/pull/347.

#### Potential Risks
None. This is documentation only.

#### Test Plan
None. This is documentation only.

### CODE REVIEW

**Comment by bradvogel** [comment]
cc @evolkmann

**Review by evolkmann — APPROVED** [review]
Sorry for that 😇

**Comment by bradvogel** [comment]
All good - I should have reviewed more carefully.

**Review by shils — APPROVED** [review]

**Pull request merged**
