### PR TITLE
feat(deps): remove dependency on `handlebars-helpers`

### LINKED ISSUE #226: Remove dependency on `handlebars-helpers`
Hello,

I am wondering if it would be possible for `arena` to drop its dependency on `handlebars-helpers`. This single dependency is responsible for *177* transitive dependencies -- you can see a particularly striking visualization of this at https://npm.anvaka.com/#!/view/2d/handlebars-helpers. 

As far as I can tell, this project does not non-trivially rely on `handlebars-helpers` for any functionality. I was able to replace presumably all uses of this library in only 6 lines,

```javascript
handlebars.registerHelper("encodeURI", encodeURIComponent);
handlebars.registerHelper("capitalize", (s) => s.charAt(0).toUpperCase() + s.slice(1));
handlebars.registerHelper("add", (a, b) => Number(a) + Number(b));
handlebars.registerHelper("subtract", (a, b) => Number(a) - Number(b));
handlebars.registerHelper("length", (a) => a.length);
handlebars.registerHelper("moment", (date, format) => moment(date).format(format));
```

### PR DESCRIPTION
**Pull request by roychri**
This pull request removes the dependency on handlebars-helpers by creating ad hoc helpers to do the same tasks.

This removes 135 transitive dependencies, making node_modules much lighter, and removes 64 vulnerabilities.

This is a continuation of pull #227 

Closes #226

### CODE REVIEW

**Comment by roychri** [comment]
@skeggse Is this what you were expecting?

**Review by skeggse — APPROVED** [review]
Yep, looks good!

**Comment by connorskees** [comment]
Thanks for finishing this!

**Pull request merged**
