### PR TITLE
Add health check for kubernetes

### PR DESCRIPTION
**Pull request by milesalex**
I'd like to use the image that y'all host but with a little health check for a k8s deployment

### CODE REVIEW

**Comment by ttacon** [comment]
Hey! Thanks for the PR! Any reason not to use the [module functionality](https://github.com/bee-queue/arena#running-arena-as-a-node-module)?

**Comment by milesalex** [comment]
@ttacon It seemed more simple to me to use the pre-packaged image with the github repo backing it with a health check included so I don't need to repeatedly pull new updates into something I host.

Does that make sense? I totally get if you think this is out of scope for arena.

**Comment by milesalex** [comment]
Agree! What would you like to see and how far off is what I have?

**Comment by milesalex** [comment]
Using root for now.

**Pull request closed without merging**
