### PR TITLE
Revert "Security fix: Upgrade jQuery to v3.5.1"

### PR DESCRIPTION
**Pull request by skeggse**
Reverts bee-queue/arena#249

Per https://github.com/bee-queue/arena/pull/249#issuecomment-711796179

cc @Piccirello, @bvallelunga, @justrealmilk - we'll likely need to switch away from the deprecated CDN `/g/` to `/npm/`

### CODE REVIEW

**Comment by Piccirello** [comment]
Apologies for my lack of testing of the jsdelivr URL. Based on your suggestion, it looks like the following URLs will work. It does mean making two separate requests as bootstrap doesn't appear to work with the `/npm/` url.

- https://cdn.jsdelivr.net/npm/jquery@3.5.1
- https://cdn.jsdelivr.net/g/bootstrap@3.3.7

I'm happy to put up PRs using these urls. Lmk!

**Comment by skeggse** [comment]
We should be able to use `bootstrap` from `npm`, no? In which case we'd be able to combine back into one under `/npm/`, I think.

**Comment by Piccirello** [comment]
jdelivr doesnt seem to likely the structure of the bootstrap repo: https://cdn.jsdelivr.net/npm/bootstrap@3.3.7

**Comment by skeggse** [comment]
https://cdn.jsdelivr.net/combine/npm/jquery@3.5.1,npm/bootstrap@3.3.7/dist/js/npm.min.js seems to work for me

**Comment by Piccirello** [comment]
I wasn't aware that jsdelivr supported such fanciness. I'll put up a new PR tonight for jQuery and Bootstrap.

**Pull request merged**
